// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bpfprog} from '../models';

export function GetEbpfProgList():Promise<Array<bpfprog.ProgramInfo>>;

export function Greet(arg1:string):Promise<string>;
