// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ebpf} from '../models';

export function GetEbpfProgList():Promise<Array<ebpf.ProgramID>>;

export function Greet(arg1:string):Promise<string>;
